sudo: false
dist: trusty
language: c
compiler:
  - gcc
cache:
  directories:
    - $HOME/.cache
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
    - re2c
env:
 - BASE=R3.14.12.8 STATIC=shared SEQ=2.2.4 ASYN=4-31 IPAC=2.14
 - BASE=R3.14.12.8 STATIC=static SEQ=2.2.4 ASYN=4-31 IPAC=2.14
 - BASE=R3.15.5 STATIC=shared SEQ=2.2.4 ASYN=4-31 IPAC=2.14
 - BASE=R3.15.5 STATIC=static SEQ=2.2.4 ASYN=4-31 IPAC=2.14
 - BASE=R7.0.1.1 STATIC=shared RTEMS=4.10 SEQ=2.2.4 ASYN=4-31 IPAC=2.14
 - BASE=R7.0.1.1 STATIC=shared CMPLR=clang WINE=32 SEQ=2.2.4 ASYN=4-31 IPAC=
 - BASE=R7.0.1.1 STATIC=static WINE=32 SEQ=2.2.4 ASYN=4-31 IPAC=
install: ./.ci/travis-prepare.sh
script: make
